[build-system]
build-backend = "mesonpy"
requires = ["meson >= 1.0.0", "meson-python >= 0.14.0"]

[project]
name = "watcher"
version = "0.12.0"
authors = [{name = "Will"}]
homepage = "https://github.com/e-dant/watcher"
description = "Filesystem watcher. Works anywhere. Simple, efficient, and friendly."
license.text = "MIT"
keywords = [ "watcher", "filesystem", "events", "async" ]
packages = [{include = "watcher"}]

[tool.cibuildwheel]
free-threaded-support = true
manylinux-x86_64-image = "manylinux2014"
manylinux-i686-image = "manylinux2014"
manylinux-pypy_x86_64-image = "manylinux2014"
manylinux-pypy_i686-image = "manylinux2014"
