#
# Android Workflow
#

# https://github.com/filipdutescu/modern-cpp-template/blob/master/.github/workflows

name: Android

on:
  push:
    branches: [ release, next ]
  pull_request:
    branches: [ release, next ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        android_ndk_revision:
          - r25b
          - r24
          - r23
          - r22b
          - r21e
          - r20b
          - r19c
          - r18b
          - r17c
        install_location:
          - .local

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip ci android]')"

    steps:
      - uses: actions/checkout@v3

      - name: Setup Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ${{github.workspace}}/${{matrix.install_location}}
            ${{github.workspace}}/build/out
            ${{github.workspace}}/cmake
          key: ${{runner.os}}-dependencies

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: ${{matrix.android_ndk_revision}}
          # Always add to path. Otherwise,
          # the wrong standard headers are found.
          add-to-path: true
          local-cache: true

      - name: Build
        run: |
          tool/build --verbose --platform-android --no-build-test --no-build-bench --no-run-test --no-run-bench
