name: Android

on:
  push:
    branches: [ release, next ]
  pull_request:
    branches: [ release, next ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    permissions:
      id-token: write
      contents: read
      attestations: write
    strategy:
      matrix:
        target-double:
          - linux-android
        target-platform:
          - android
        android-ndk-major-version:
          - '25'
          - '26'
        os:
          - ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        with:
          path: out
          key: cache.${{matrix.target-double}}.${{matrix.os}}
      - run: |
          export ANDROID_NDK_HOME=$(find /usr/local/lib/android/sdk/ndk -type d -maxdepth 1 -name '${{matrix.android-ndk-major-version}}*' | head -n 1)
          tool/build --verbose --platform-${{matrix.target-platform}} --no-build-test --no-run
      - run: tool/bundle-artifacts minimal-artifacts/${{matrix.target-double}} ${{matrix.target-platform}}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.target-double}}.built-on-${{matrix.os}}.used-ndk-${{matrix.android-ndk-major-version}}
          path: minimal-artifacts/${{matrix.target-double}}.tar.gz
      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: minimal-artifacts
      - run: tool/test/all
      - run: tool/build --verbose --no-build --no-run-perf
      - run: tool/build --verbose --no-build --no-run-unit
      - run: ls -al out/${{matrix.target-platform}}/Debug
      - run: ls -al out/${{matrix.target-platform}}/Release
