#
# Android Workflow
#

# https://github.com/filipdutescu/modern-cpp-template/blob/master/.github/workflows

name: Android

on:
  push:
    branches: [ release, next ]
  pull_request:
    branches: [ release, next ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - clang-13.0.0
        compiler_c_short_name:
          - clang
        compiler_cxx_short_name:
          - clang++
        build_type:
          - Release
        install_location:
          - .local
        developer_mode:
          - OFF

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip ci android]')"

    steps:
      - uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ${{github.workspace}}/${{matrix.install_location}}
            ${{github.workspace}}/build/out
            ${{github.workspace}}/cmake
          key: ${{runner.os}}-dependencies

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25b
          # Always add to path. Otherwise,
          # the wrong standard headers are found.
          add-to-path: true
          local-cache: true

      #- name: Setup Cpp
      #  uses: aminya/setup-cpp@v1
      #  with:
      #    compiler: ${{matrix.compiler}}
      #    vcvarsall: ${{contains(matrix.os, 'windows')}}
      #    cmake: true
      #    ccache: false
      #    ninja: true
      #    conan: false
      #    vcpkg: false
      #    gcovr: false
      #    cppcheck: false
      #    clangtidy: false
      #    opencppcoverage: false

      - name: Build and Test
        run: |
          build/build android --no-build-debug
          build/out/android/release/wtr.watcher . -s 1
