#
# Android Workflow
#

# https://github.com/filipdutescu/modern-cpp-template/blob/master/.github/workflows

name: Android

on:
  push:
    branches: [ release, next ]
  pull_request:
    branches: [ release, next ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        android_ndk_maj_v:
          - '24'
          - '25'
          - '26'
        install_location:
          - .local
    steps:
      - uses: actions/checkout@v3
      - run: |
          export CMAKE_ANDROID_API=34
          export ANDROID_NDK_HOME=$(find /usr/local/lib/android/sdk/ndk -type d -maxdepth 1 -name '${{matrix.android_ndk_maj_v}}*' | head -n 1)
          tool/build --verbose --platform-android --no-build-test --no-run-test
