name: libcwatcher

on:
  push:
    branches: [ release, next ]
  pull_request:
    branches: [ release, next ]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target-triple:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        with:
          path: ${{matrix.target-triple}}
          key: cache.libcwatcher.${{matrix.target-triple}}.build
          restore-keys: |
            cache.libcwatcher.${{matrix.target-triple}}.build
      - uses: actions/cache@v3
        with:
          path: /var/cache/apt/archives
          key: cache.libcwatcher.${{matrix.target-triple}}.apt-cache
          restore-keys: |
            cache.libcwatcher.${{matrix.target-triple}}.apt-cache
      - run: |
          which python3 || apt-get install -yqq python3 python3-pip python3-setuptools python3-wheel ninja-build
          which meson || pip3 install meson
      - run: |
          meson setup --cross-file libcwatcher/cross-files/${{matrix.target-triple}}.txt ${{matrix.target-triple}}
          meson compile -C ${{matrix.target-triple}}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.target-triple}}
          path: ${{matrix.target-triple}}
