#
# macOS Workflow
#

# https://github.com/filipdutescu/modern-cpp-template/blob/master/.github/workflows

name: macOS

on:
  push:
    branches: [ release, next ]
  pull_request:
    branches: [ release, next ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        cxx_compiler:
          - clang++
        install_location:
          - .local

    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip ci macos]')"

    steps:
      - uses: actions/checkout@v3

      - name: Setup Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ${{github.workspace}}/${{matrix.install_location}}
            ${{github.workspace}}/build/out
          key: ${{runner.os}}-dependencies

      - name: Build
        run: |
          export CXX="$(which "${{matrix.cxx_compiler}}")"
          tool/build --no-run

      - name: Test
        run: |
          tool/build --no-build
