#
# macOS Workflow
#

# https://github.com/filipdutescu/modern-cpp-template/blob/master/.github/workflows

name: macOS

on:
  push:
    branches: [ release, next ]
  pull_request:
    branches: [ release, next ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        language:
          [ 'cpp' ]
        compiler:
          - clang-13.0.0
        compiler_c_short_name:
          - clang
        compiler_cxx_short_name:
          - clang++
        build_type:
          - Release
        install_location:
          - .local
        developer_mode:
          - OFF

    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip ci macos]')"

    steps:
      - uses: actions/checkout@v3

      - name: Setup Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ${{github.workspace}}/${{matrix.install_location}}
            ${{github.workspace}}/build/out
          key: ${{runner.os}}-dependencies

      - name: Build
        run: |
          export CXX=$(which ${{matrix.compiler_cxx_short_name}})
          build/build --no-build-debug --no-run-test

      - name: Test
        run: |
          build/build --no-build-release --no-build-debug --no-build-test
          build/out/this/release/wtr.watcher . -s 5 &
          build/out/this/debug/asan/wtr.watcher . -s 5 &
          build/out/this/debug/msan/wtr.watcher . -s 5 &
          build/out/this/debug/ubsan/wtr.watcher . -s 5 &
          build/out/this/debug/nosan/wtr.watcher . -s 5 &
          build/out/this/release/wtr.watcher "$PWD" -s 5 &
          build/out/this/debug/asan/wtr.watcher "$PWD" -s 5 &
          build/out/this/debug/msan/wtr.watcher "$PWD" -s 5 &
          build/out/this/debug/ubsan/wtr.watcher "$PWD" -s 5 &
          build/out/this/debug/nosan/wtr.watcher "$PWD" -s 5 &
