#
# macOS Workflow
#

# https://github.com/filipdutescu/modern-cpp-template/blob/master/.github/workflows

name: macOS

on:
  push:
    branches: [ release, next ]
  pull_request:
    branches: [ release, next ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - clang-13.0.0
        compiler_c_short_name:
          - clang
        compiler_cxx_short_name:
          - clang++
        build_type:
          - Release
        install_location:
          - .local
        developer_mode:
          - OFF

    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v3
      - name: Build and Test
        run: |
          export CXX=$(which clang++)
          build/build this --no-build-debug
          build/out/this/release/wtr.watcher . -s 1

