name: macOS

on:
  push:
    branches: [ release, next ]
  pull_request:
    branches: [ release, next ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - macos-11
          - macos-12
          - macos-13
        cxx_compiler:
          - clang++
        install_location:
          - .local
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
      - uses: actions/cache@v3
        with:
          path: |
            ${{github.workspace}}/${{matrix.install_location}}
            ${{github.workspace}}/out
          key: macos-${{runner.os}}-${{matrix.os}}-dependencies
      - run: |
          tool/build --verbose --no-run
          ls -al out/this/Debug
          ls -al out/this/Release
      - run: tool/build --verbose --no-build
      - run: tool/test/all || tool/test/all
