#
# MacOS Workflow
#

# https://github.com/filipdutescu/modern-cpp-template/blob/master/.github/workflows

name: MacOS

on:
  push:
    branches: [ release, next ]
  pull_request:
    branches: [ release, next ]

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: .local

jobs:
  build:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v2
      id: cache
      with:
        path: ${{ github.workspace }}/${{ env.INSTALL_LOCATION }}
        key: ${{ runner.os }}-dependencies

    - name: Configure
      run: cmake -S build/in -B build/out -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/$INSTALL_LOCATION

    - name: Build
      run: cmake --build build/out --config $BUILD_TYPE -j4

    # @TODO(will) Our tests require a running binary
    # - name: Test
    #   run: |
    #     cd build
    #     ctest -C $BUILD_TYPE -VV

    - name: Install
      run: cmake --build build/out --target install --config Release 

