name: Ubuntu

on:
  push:
    branches: [ release, next ]
  pull_request:
    branches: [ release, next ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    fail-fast: false
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-latest
        cxx_compiler:
          # See issue 41 re. clang++
          - g++
        install_location:
          - .local
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ${{github.workspace}}/${{matrix.install_location}}
            ${{github.workspace}}/out
          key: ubuntu-${{runner.os}}-${{matrix.os}}-dependencies
      - run: |
          tool/build --verbose --no-run
          ls -al out/this/Debug
          ls -al out/this/Release
      - run: tool/build --verbose --no-build
      - run: sudo tool/build --verbose --no-build
      - run: tool/test/all || tool/test/all
      - run: sudo tool/test/all || sudo tool/test/all

