#
# Ubuntu Workflow
#

# In the 'Test' step, we could do something like this:
#   build/out/this/Release/wtr.watcher . -s 5 &
#   build/out/this/Release/wtr.watcher.asan . -s 5 &
#   build/out/this/Release/wtr.watcher.ubsan . -s 5 &
#   build/out/this/Debug/wtr.watcher . -s 5 &
#   build/out/this/Debug/wtr.watcher.asan . -s 5 &
#   build/out/this/Debug/wtr.watcher.ubsan . -s 5 &
#   wait
# To see if the cli works as intended. But, if they don't finish,
# that might be a lot of money if I forget to stop the runner...

# https://github.com/filipdutescu/modern-cpp-template/blob/master/.github/workflows

name: Ubuntu

on:
  push:
    branches: [ release, next ]
  pull_request:
    branches: [ release, next ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        cxx_compiler:
          - clang++
        install_location:
          - .local

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip ci ubuntu]')"

    steps:
      - uses: actions/checkout@v3

      - name: Setup Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ${{github.workspace}}/${{matrix.install_location}}
            ${{github.workspace}}/build/out
          key: ${{runner.os}}-dependencies

      - name: Build
        run: |
          export CXX=$(which ${{matrix.cxx_compiler}})
          tool/build --no-run

      - name: Test
        run: |
          tool/build --no-build
