#
# Windows Workflow
#

# https://github.com/filipdutescu/modern-cpp-template/blob/master/.github/workflows

name: Windows

on:
  push:
    branches: [ release, next ]
  pull_request:
    branches: [ release, next ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        language:
          [ 'cpp' ]
        compiler:
          - msvc
        compiler_c_short_name:
          - msvc
        compiler_cxx_short_name:
          - msvc
        build_type:
          - Release
        install_location:
          - .local
        developer_mode:
          - OFF

    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip ci windows]')"

    steps:
      - uses: actions/checkout@v3

      - name: Setup Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ${{github.workspace}}/${{matrix.install_location}}
            ${{github.workspace}}/build/out
            ${{github.workspace}}/cmake
          key: ${{runner.os}}-dependencies

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{matrix.compiler}}
          vcvarsall: ${{contains(matrix.os, 'windows')}}
          cmake: true
          ccache: false
          ninja: false
          conan: false
          vcpkg: false
          gcovr: false
          cppcheck: false
          clangtidy: false
          opencppcoverage: false

      - name: Build
        run: |
          bash -c 'build/build --no-run-test'

      - name: Test
        run: |
          bash -c 'while read -r P; do if test -n "$P"; then eval "$P" -s 2; fi; done <<< "$(find . -name wtr.watcher.\*.exe)"'
          bash -c 'while read -r T; do if test -n "$T"; then eval "$T"; fi; done <<< "$(find . -name wtr.test_watcher.\*.exe)"'

