#
# Windows Workflow
#

# https://github.com/filipdutescu/modern-cpp-template/blob/master/.github/workflows

name: Windows

on:
  push:
    branches: [ release, next ]
  pull_request:
    branches: [ release, next ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - msvc
        compiler_c_short_name:
          - msvc
        compiler_cxx_short_name:
          - msvc
        build_type:
          - Release
        install_location:
          - .local
        developer_mode:
          - OFF

    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          export CXX=$(which msvc)
          rm -rf build/out && build/build
      - name: Test Runnable
        run: |
          build/out/this/release/water.watcher . -s 1
          build/out/this/debug/asan/water.watcher . -s 1
          build/out/this/debug/msan/water.watcher . -s 1
          build/out/this/debug/tsan/water.watcher . -s 1
          build/out/this/debug/ubsan/water.watcher . -s 1
          build/out/this/debug/stacksan/water.watcher . -s 1
          build/out/this/debug/cfisan/water.watcher . -s 1
