#
# Windows Workflow
#

# https://github.com/filipdutescu/modern-cpp-template/blob/master/.github/workflows

name: Windows

on:
  push:
    branches: [ release, next ]
  pull_request:
    branches: [ release, next ]

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: .local

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - llvm-13.0.0
          - gcc-12
        generator:
          - "Ninja"
        build_type:
          - Release
        developer_mode:
          - OFF

    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v2
      id: cache
      with:
        path: ${{ github.workspace }}/${{ env.INSTALL_LOCATION }}
        key: ${{ runner.os }}-dependencies

    - name: Configure
      run: cmake -S build/in -B build/out -G "${{ matrix.generator }}" -DCMAKE_CXX_COMPILER=${{matrix.compiler}} -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/$INSTALL_LOCATION

    - name: Build
      run: cmake --build build/out --config ${{ matrix.build_type }} -j4

    # @TODO(will) Our tests require a running binary
    # - name: Test
    #   run: |
    #     tool/test/file
    #     tool/test/dir

    - name: Install
      run: cmake --build build/out --target install --config Release 

