name: Windows

on:
  push:
    branches: [ release, next ]
  pull_request:
    branches: [ release, next ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2022
          - windows-2019
    steps:
      - uses: actions/checkout@v4
      - uses: aminya/setup-cpp@v1
        with:
          compiler: 'msvc'
          vcvarsall: true # Truly a masterpiece, what a great idea Windows :)
          cmake: true
          ccache: false
          ninja: false
          conan: false
          vcpkg: false
          gcovr: false
          cppcheck: false
          clangtidy: false
          opencppcoverage: false
      - run: |
          cl.exe src/wtr/tiny_watcher/main.cpp /Iinclude /std:c++17 /O2 /EHs /EHr /EHc /Fe:tiny.exe
          bash -c 'ls -hal tiny.exe'
      - shell: bash
        run: |
          cmake -S . -B out/manual ; cmake --build out/manual --target wtr.test_watcher --config Release
          cmake -S . -B out/manual ; cmake --build out/manual --target wtr.test_watcher --config Debug
      - shell: bash
        env:
          VERBOSE: 1
        run: |
          out/manual/Debug/wtr.test_watcher.exe || echo f windows
          out/manual/Release/wtr.test_watcher.exe || echo f windows
      - run: echo windows is an abomination

