#
# Windows Workflow
#

# https://github.com/filipdutescu/modern-cpp-template/blob/master/.github/workflows

name: Windows

on:
  push:
    branches: [ release, next ]
  pull_request:
    branches: [ release, next ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - msvc
        build_type:
          - Release
        install_location:
          - .local
        developer_mode:
          - OFF

    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v2

    - name: Setup Cpp
      uses: aminya/setup-cpp@v1
      with:
        compiler: ${{ matrix.compiler }}
        vcvarsall: ${{ contains(matrix.os, 'windows' )}}
        cmake: true
        ninja: true
        conan: true
        vcpkg: false
        ccache: true
        clangtidy: false
        cppcheck: false
        gcovr: false
        opencppcoverage: false

    - name: Cache
      uses: actions/cache@v2
      id: cache
      with:
        path: ${{ github.workspace }}/${{ matrix.install_location }}
        key: ${{ runner.os }}-dependencies

    - name: Configure
      env:
        CC: ${{ matrix.compiler }}
        CXX: ${{ matrix.compiler }}
      run: cmake -S build/in -B build/out -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/$INSTALL_LOCATION

    - name: Build
      env:
        CC: ${{ matrix.compiler }}
        CXX: ${{ matrix.compiler }}
      run: cmake --build build/out --config ${{ matrix.build_type }} -j4

    # @TODO(will) Our tests require a running binary
    # - name: Test
    #   run: |
    #     tool/test/file
    #     tool/test/dir

    - name: Install
      env:
        CC: ${{ matrix.compiler }}
        CXX: ${{ matrix.compiler }}
      run: cmake --build build/out --target install --config Release 

